print("Hello, World!")
print("Welcome to the Wallet System!")
print("You can add balance, make payments, and check your balance.")
print("Let's get started!")
print("Please follow the instructions to manage your wallet effectively.")