print("Hello This is Aononto Jahan Junnurain")
print("I am a student of Computer Science and Engineering")
print("I am in final year")
print("I am a student of International University of Business Agriculture and Technology")
print("I am from Bangladesh")
print("I am 25 years old")
print("I am a programmer")